title:              Welcome to blog Uoc Nguyen
email:              vanuoc.haui@gmail.com
description:        A Blog by Uoc Nguyen
author:             Uoc Nguyen
baseurl:            "/"
url:                "https://nguyenvanuoc.github.io"

plugins:
  - jekyll-get-json